# Указываем используемый Docker-образ
image: aergus/latex:latest

# Определяем стадии пайплайна
stages:
  - build

# Задача компиляции PDF
compile_pdf:
  stage: build
  script:
    - cd latex
    - pdflatex main
    - biber main
    - pdflatex main
    - pdflatex main
  artifacts:
    paths:
      - main.pdf
    expire_in: 7 days
