name: Update Latest Release PDF

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write               # Разрешить создание/обновление релиза

jobs:
  update-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: latex
          root_file: main.tex
          args: "-pdf -halt-on-error -file-line-error -interaction=nonstopmode"

      - name: Update release with new PDF
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest            # Релиз, привязанный к тегу latest
          name: "Актуальный конспект"
          draft: false
          prerelease: false
          files: latex/main.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}